name: MarvelApp
options:
  createIntermediateGroups: true
  indentWidth: 4
  tabWidth: 4
  bundleIdPrefix: "sof.frakcool.MarvelApp"
targets:
  MarvelApp:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: MarvelApp
    dependencies:
      - package: Moya
      - target: Presentation
      - target: Domain
      - target: Data
  MarvelApp-iOS-Tests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: MarvelAppTests
    dependencies:
      - target: MarvelApp
  Data:
    type: framework
    platform: iOS
    deploymentTarget: "14.0"
    sources: "Frameworks/Data"
    settings:
        base:
            PRODUCT_BUNDLE_IDENTIFIER: ${BUNDLE_IDENTIFIER}.data.framework
    dependencies:
      - package: Moya
      - package: Alamofire
  Domain:
    type: framework
    platform: iOS
    deploymentTarget: "14.0"
    sources: "Frameworks/Domain"
    settings:
        base:
            PRODUCT_BUNDLE_IDENTIFIER: ${BUNDLE_IDENTIFIER}.domain.framework
    dependencies:
      - target: Data
  Presentation:
    type: framework
    platform: iOS
    deploymentTarget: "14.0"
    sources: "Frameworks/Presentation"
    settings:
        base:
            PRODUCT_BUNDLE_IDENTIFIER: ${BUNDLE_IDENTIFIER}.presentation.framework
    dependencies:
      - target: Domain
packages:
  Moya:
    from: "14.0.0"
    url: "https://github.com/Moya/Moya"
  Alamofire:
    from: "5.4"
    url: "https://github.com/Alamofire/Alamofire"
